//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportare.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMenu()
        {
            this.AsignarPrivilegio = new HashSet<AsignarPrivilegio>();
        }
    
        public int IdModulo { get; set; }
        public int IdMenu { get; set; }
        public int IdSubMenu { get; set; }
        public string NomSubMenu { get; set; }
        public string IconSubMenu { get; set; }
        public string URL { get; set; }
        public int IdEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignarPrivilegio> AsignarPrivilegio { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
